import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :my_super_app, MySuperAppWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Configures Swoosh API Client
config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: MySuperApp.Finch

# Disable Swoosh Local Memory Storage
config :swoosh, local: false

# config :swoosh, api_client: Swoosh.ApiClient.Finch, finch_name: MySuperApp.Finch
# config :swoosh, local: false  # Disable local memory storage

# Do not print debug messages in production
config :logger, level: :debug

config :esbuild,
  version: "0.16.4",
  default: [
    args: ~w(js/app.js --bundle --target=es2016 --outdir=../priv/static/assets),
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

config :cloudex,
  api_key: "928868927816978",
  secret: "FOaBn0P6Rrq8xKCrxp2FznAJGr0",
  cloud_name: "ddmjy9yfs"

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
